name: Test Teraslice Asset
run-name: ${{ github.actor }} is testing the Teraslice Asset
on:
  workflow_dispatch:
  push:
    branches:
      - release/file-assets-v*
  pull_request:
    branches:
      - release/file-assets-v*
jobs:
  call-asset-test-workflow:
    uses: terascope/workflows/.github/workflows/prerelease-asset-test.yml@main
    secrets: inherit
